<?php
/**
 * Created by PhpStorm.
 * User: swxua
 * Date: 2017/10/22
 * Time: 16:23
 */

namespace Proxy\Middleware;

use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;

class ExampleMiddleware extends BasicMiddleware
{
    public function beforeAction(RequestInterface $request)
    {
        //return parent::beforeAction($request); // TODO: Change the autogenerated stub
        return $request;
    }

    public function afterAction(ResponseInterface $response)
    {
        //return parent::afterAction($response); // TODO: Change the autogenerated stub
        return $response;
    }
}